/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.ThongKeSach;
import Until.ThongKes;

/**
 *
 * @author admin
 */
public class ThongKe extends javax.swing.JFrame {

    ArrayList<ThongKeSach> listbookmanager = new ArrayList();
    ThongKeSach booktk;
    private static int position = 0;
    private static int check = 0;

    public ThongKe() {
        initComponents();
        laydulieuthongke();
    }

    public void view() {
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        try {
            ThongKeSach tk = new ThongKeSach();
            model.setNumRows(0);
            for (ThongKeSach s : listbookmanager) {
                model.addRow(new Object[]{s.getMathongke(), s.getBookID(), s.getNgaythongke(), s.getSoluongton()});
            }
            model.fireTableDataChanged();
            OnOffButton(false, true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void laydulieuthongke() {
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        try {
            ThongKes tks = new ThongKes();
            listbookmanager = tks.docFileBook();
            ThongKeSach tk = new ThongKeSach();
            model.setNumRows(0);
            for (ThongKeSach s : listbookmanager) {
                model.addRow(new Object[]{s.getMathongke(), s.getBookID(), s.getNgaythongke(), s.getSoluongton()});
            }
            model.fireTableDataChanged();
            OnOffButton(false, true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComeBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangthongke = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMSTK = new javax.swing.JTextField();
        txtBookID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtQuanlity = new javax.swing.JTextField();
        AddBook = new javax.swing.JButton();
        UpdateBook = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        SearchBook = new javax.swing.JButton();
        NoConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComeBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/returnn2.jpg"))); // NOI18N
        ComeBack.setText("Quay lại");
        ComeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComeBackActionPerformed(evt);
            }
        });
        jPanel1.add(ComeBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thống kê sách");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        bangthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Mã số thống kê", "Mã sách", "Ngày thống kê", "Số lượng trong kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangthongkeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangthongke);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 796, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã số thống kê");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã sách");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtMSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMSTKActionPerformed(evt);
            }
        });
        jPanel1.add(txtMSTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, -1));

        txtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày thống kê");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng tồn");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 160, -1));
        jPanel1.add(txtQuanlity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 160, -1));

        AddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add1.png"))); // NOI18N
        AddBook.setText("Thêm");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });
        jPanel1.add(AddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 323, 140, 40));

        UpdateBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit1.png"))); // NOI18N
        UpdateBook.setText("Cập nhật");
        UpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 323, 140, 40));

        DeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete1.png"))); // NOI18N
        DeleteBook.setText("Xóa");
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 383, 140, 40));

        Confirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save2.png"))); // NOI18N
        Confirm.setText("Đồng ý");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 443, 140, 40));

        SearchBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search1.jpg"))); // NOI18N
        SearchBook.setText("Tìm kiếm");
        SearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 383, 140, 40));

        NoConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NoConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel1.png"))); // NOI18N
        NoConfirm.setText("Hủy bỏ");
        NoConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(NoConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 443, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMSTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMSTKActionPerformed

    private void txtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIDActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        OnOffButton(true, false);
        check = 1;
    }//GEN-LAST:event_AddBookActionPerformed

    private void ComeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComeBackActionPerformed
        TrangChu1 tc = new TrangChu1();
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComeBackActionPerformed

    private void UpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookActionPerformed
        OnOffButton(true, false);
        check = -1;
    }//GEN-LAST:event_UpdateBookActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        OnOffButton(true, false);
        check = -2;
    }//GEN-LAST:event_DeleteBookActionPerformed
    public static int tb = 0;
    private void SearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookActionPerformed
        outsearching(true, false);
        String id = this.txtMSTK.getText();
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        model.setNumRows(0);
        for (ThongKeSach s : listbookmanager) {
            if (id.equals(s.getMathongke())) {
                tb++;
                model.addRow(new Object[]{s.getMathongke(), s.getBookID(), s.getNgaythongke(), s.getSoluongton()});
            }
        }
        if (tb == 0) {
            JOptionPane.showConfirmDialog(this, "Khong co so thong ke phu hop", "Thong bao", JOptionPane.ERROR_MESSAGE);
        }
        check = 2;
    }//GEN-LAST:event_SearchBookActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        String id = this.txtMSTK.getText();
        String bookid = this.txtBookID.getText();
        String date = this.txtTime.getText();
        String sl = this.txtQuanlity.getText();
        StringBuilder sb = new StringBuilder();
        if (id.equals("")) {
            sb.append("Không được để trống mã số thống kê!\n");
        }
        if (bookid.equals("")) {
            sb.append("Không được để trống mã sách!\n");
        }
        if (date.trim().equals("")) {
            sb.append("Không được để trống ngày thống kê!\n");
        }
        if (sl.trim().equals("")) {
            sb.append("Không được để trống số lượng tồn kho!\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Invaidation", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            if (check == 1) {
                try {
                    ThongKes tks = new ThongKes();
                    String kt = txtMSTK.getText();
                    int dem = 0;
                    for (ThongKeSach t : listbookmanager) {
                        if (kt.equals(t.getMathongke())) {
                            dem++;
                        }
                    }
                    if (dem == 0) {
                        ThongKeSach s = new ThongKeSach(txtMSTK.getText(), txtBookID.getText(), txtTime.getText(), txtQuanlity.getText());
                        listbookmanager.add(s);
                        tks.luuFile(listbookmanager, false);
                        JOptionPane.showMessageDialog(this, "Đã lưu thành công!", "Trạng thái", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Đã tồn tại bản thống kê này!", "Trạng thái", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else if (check == -1) {
                try {
                    ThongKes tks = new ThongKes();
                    ThongKeSach s = new ThongKeSach(txtMSTK.getText(), txtBookID.getText(), txtTime.getText(), txtQuanlity.getText());
                    listbookmanager.set(position, s);
                    tks.luuFile(listbookmanager, false);
                    JOptionPane.showMessageDialog(this, "Đã sửa thành công!", "Trạng thái", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else if (check == -2) {
                try {
                    ThongKes tks = new ThongKes();
                    listbookmanager.remove(position);
                    JOptionPane.showConfirmDialog(this, "Đã xóa thành công!", "Trạng thái", JOptionPane.ERROR_MESSAGE);
                    tks.luuFile(listbookmanager, false);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        laydulieuthongke();
    }//GEN-LAST:event_ConfirmActionPerformed

    private void bangthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangthongkeMouseClicked
        position = this.bangthongke.getSelectedRow();
        ThongKeSach s = listbookmanager.get(position);
        this.txtMSTK.setText(s.getMathongke());
        this.txtBookID.setText(s.getBookID());
        this.txtTime.setText(s.getNgaythongke());
        this.txtQuanlity.setText(s.getSoluongton());
    }//GEN-LAST:event_bangthongkeMouseClicked

    private void NoConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoConfirmActionPerformed
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        OnOffButton(false, true);
        if (check == 2) {
            laydulieuthongke();
        }
    }//GEN-LAST:event_NoConfirmActionPerformed

    private void OnOffButton(boolean a, boolean b) {
        this.Confirm.show(a);
        this.NoConfirm.show(a);
        this.AddBook.show(b);
        this.DeleteBook.show(b);
        this.SearchBook.show(b);
        this.UpdateBook.show(b);
    }

    private void outsearching(boolean a, boolean b) {
        this.NoConfirm.show(a);
        this.Confirm.show(b);
        this.AddBook.show(b);
        this.DeleteBook.show(b);
        this.SearchBook.show(b);
        this.UpdateBook.show(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton ComeBack;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JButton NoConfirm;
    private javax.swing.JButton SearchBook;
    private javax.swing.JButton UpdateBook;
    private javax.swing.JTable bangthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtMSTK;
    private javax.swing.JTextField txtQuanlity;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
