/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author DELL 5625
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        qlyPhieuMuon = new javax.swing.JLabel();
        qlyPhieuTra = new javax.swing.JLabel();
        QlyNguoiDoc = new javax.swing.JLabel();
        qlySach = new javax.swing.JLabel();
        ThongKe = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search-icon (3).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("I");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 20, 80));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Man-2-icon.png"))); // NOI18N
        jLabel6.setText("HI,ADMIN !");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Mail-icon.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("I");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bell-icon (1).png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 50, 50));

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 3, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/library.png"))); // NOI18N
        jLabel10.setText("Library");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, -1, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("I");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, 20, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu-icon (1).png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1930, 80));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Features");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 30));

        qlyPhieuMuon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qlyPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        qlyPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/a.png"))); // NOI18N
        qlyPhieuMuon.setText("Quản lý phiếu mượn");
        qlyPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlyPhieuMuonMouseClicked(evt);
            }
        });
        jPanel5.add(qlyPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, 50));

        qlyPhieuTra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qlyPhieuTra.setForeground(new java.awt.Color(255, 255, 255));
        qlyPhieuTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/b.png"))); // NOI18N
        qlyPhieuTra.setText("Quản lý phiếu trả");
        qlyPhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlyPhieuTraMouseClicked(evt);
            }
        });
        jPanel5.add(qlyPhieuTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        QlyNguoiDoc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        QlyNguoiDoc.setForeground(new java.awt.Color(255, 255, 255));
        QlyNguoiDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/d.png"))); // NOI18N
        QlyNguoiDoc.setText("Quản lý người đọc");
        jPanel5.add(QlyNguoiDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        qlySach.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qlySach.setForeground(new java.awt.Color(255, 255, 255));
        qlySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/e.png"))); // NOI18N
        qlySach.setText("Quản lý sách");
        qlySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlySachMouseClicked(evt);
            }
        });
        jPanel5.add(qlySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/i.png"))); // NOI18N
        ThongKe.setText("Thống kê");
        jPanel5.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 160, -1));

        logOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 0));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Power-icon.png"))); // NOI18N
        logOut.setText("Log out");
        jPanel5.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 140, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/k.png"))); // NOI18N
        jLabel12.setText("Library management software");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 70));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home-folded-icon.png"))); // NOI18N
        jLabel1.setText("Home");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 770));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button-Close-icon_1.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 50, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 670));

        bg.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(101, 101, 209));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 51, 102));
        jPanel10.setForeground(new java.awt.Color(51, 204, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach1.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 220));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 180, 240));

        jPanel6.setBackground(new java.awt.Color(23, 23, 112));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hoangtube.png"))); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 220));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 180, 240));

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach3.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 220));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 170, 240));

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 51, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach4.png"))); // NOI18N
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 230));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 170, 240));

        jPanel11.setBackground(new java.awt.Color(0, 51, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach7.png"))); // NOI18N
        jPanel11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 210));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 180, 230));

        jPanel12.setBackground(new java.awt.Color(0, 51, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach8.png"))); // NOI18N
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 210));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 170, 230));

        jPanel13.setBackground(new java.awt.Color(0, 51, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(0, 51, 102));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach10.png"))); // NOI18N
        jPanel13.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 210));

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 170, 230));

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nice.png"))); // NOI18N
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 520));

        jLabel33.setBackground(new java.awt.Color(255, 255, 0));
        jLabel33.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 0));
        jLabel33.setText("Online Library");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 280, -1));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 390, 570));

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sach6.png"))); // NOI18N
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 210));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 160, 230));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 660, 10));
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 360, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-icon.png"))); // NOI18N
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        bg.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 1290, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        openMenu();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        closeMenu();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void qlySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlySachMouseClicked
           bookManager dt1 = new bookManager();
            dt1.setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_qlySachMouseClicked

    private void qlyPhieuTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlyPhieuTraMouseClicked
  
    }//GEN-LAST:event_qlyPhieuTraMouseClicked

    private void qlyPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlyPhieuMuonMouseClicked
            
    }//GEN-LAST:event_qlyPhieuMuonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QlyNguoiDoc;
    private javax.swing.JLabel ThongKe;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel qlyPhieuMuon;
    private javax.swing.JLabel qlyPhieuTra;
    private javax.swing.JLabel qlySach;
    // End of variables declaration//GEN-END:variables
int width = 330;
    int height = 950;
   
    private void openMenu() {
        new Thread(new Runnable() {
            public void run() {
                for (int i = 0; i < width; i++) {
                    jPanel3.setSize(i, height);
                    try {
                        Thread.sleep(1);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();

    }

    private void closeMenu() {
        new Thread(new Runnable() {
            public void run() {
                for (int i = width; i > 0; i--) {
                    jPanel3.setSize(i, height);
                    try {
                        Thread.sleep(1);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
}
