/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author DELL 5625
 */
public class TrangChu1 extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu1
     */
    public TrangChu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLogOut = new javax.swing.JLabel();
        txtQLPhieuMuon = new javax.swing.JLabel();
        txtQLPhieuTra = new javax.swing.JLabel();
        txtQLNguoiDoc = new javax.swing.JLabel();
        txtQLSach = new javax.swing.JLabel();
        txtThongKe = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 100, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a0.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("|");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a4.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("|");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("|");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 10, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 40));

        jLabel8.setFont(new java.awt.Font("Rage Italic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Hi,admin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d6.png"))); // NOI18N
        jLabel21.setText("Library management");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 240, 40));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/e1.png"))); // NOI18N
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel27.setText("Tìm kiếm");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 60));

        jPanel2.setBackground(new java.awt.Color(57, 199, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(28, 127, 193));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a5.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 50));

        txtLogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLogOut.setForeground(new java.awt.Color(255, 255, 255));
        txtLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b4.png"))); // NOI18N
        txtLogOut.setText("Log out");
        txtLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogOutMouseClicked(evt);
            }
        });
        jPanel2.add(txtLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 220, 40));

        txtQLPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQLPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        txtQLPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a9.png"))); // NOI18N
        txtQLPhieuMuon.setText("Quản lý phiếu mượn");
        txtQLPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQLPhieuMuonMouseClicked(evt);
            }
        });
        jPanel2.add(txtQLPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 40));

        txtQLPhieuTra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQLPhieuTra.setForeground(new java.awt.Color(255, 255, 255));
        txtQLPhieuTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a7.png"))); // NOI18N
        txtQLPhieuTra.setText("Quản lý phiếu trả");
        txtQLPhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQLPhieuTraMouseClicked(evt);
            }
        });
        jPanel2.add(txtQLPhieuTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 40));

        txtQLNguoiDoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQLNguoiDoc.setForeground(new java.awt.Color(255, 255, 255));
        txtQLNguoiDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b1.png"))); // NOI18N
        txtQLNguoiDoc.setText("Quản lý người đọc");
        txtQLNguoiDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQLNguoiDocMouseClicked(evt);
            }
        });
        jPanel2.add(txtQLNguoiDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 40));

        txtQLSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQLSach.setForeground(new java.awt.Color(255, 255, 255));
        txtQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b2.png"))); // NOI18N
        txtQLSach.setText("Quản lý sách");
        txtQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQLSachMouseClicked(evt);
            }
        });
        jPanel2.add(txtQLSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 40));

        txtThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThongKe.setForeground(new java.awt.Color(255, 255, 255));
        txtThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b3.png"))); // NOI18N
        txtThongKe.setText("Thống kê");
        txtThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThongKeMouseClicked(evt);
            }
        });
        jPanel2.add(txtThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 510));

        jSeparator1.setForeground(new java.awt.Color(27, 27, 175));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 630, 10));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tài liệu mới cập nhật");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 630, 20));

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel20.setBackground(new java.awt.Color(0, 153, 255));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tài liệu được xem nhiều");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c1.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, 190));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d5.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 150, 190));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c4.png"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 150, 190));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c5.png"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 150, 190));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c3.png"))); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 150, 190));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c7.png"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, 190));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d1.png"))); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 150, 190));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d3.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 150, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQLSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQLSachMouseClicked
        bookManager dt1 = new bookManager();
        dt1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtQLSachMouseClicked

    private void txtLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogOutMouseClicked
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtLogOutMouseClicked

    private void txtQLPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQLPhieuMuonMouseClicked
        QLPhieuMuon qlpm = new QLPhieuMuon();
        qlpm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtQLPhieuMuonMouseClicked

    private void txtQLNguoiDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQLNguoiDocMouseClicked
        ReaderInterface ri = new ReaderInterface();
        ri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtQLNguoiDocMouseClicked

    private void txtThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThongKeMouseClicked
        ThongKe tk = new ThongKe();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtThongKeMouseClicked

    private void txtQLPhieuTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQLPhieuTraMouseClicked
        QuanLyPhieuTra qlpt = new QuanLyPhieuTra();
        qlpt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtQLPhieuTraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtLogOut;
    private javax.swing.JLabel txtQLNguoiDoc;
    private javax.swing.JLabel txtQLPhieuMuon;
    private javax.swing.JLabel txtQLPhieuTra;
    private javax.swing.JLabel txtQLSach;
    private javax.swing.JLabel txtThongKe;
    // End of variables declaration//GEN-END:variables
}
