/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ThongKeSach;

import static com.mycompany.bookmanager.ReaderInterface.tb;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ThongKe extends javax.swing.JFrame {

    ArrayList<ThongKeSach> listbookmanager = new ArrayList();
    ThongKeSach booktk;
    private static int position = 0;
    private static int check = 0;
    public ThongKe() {
        initComponents();
        laydulieuthongke();
    }
    public void view(){
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        try{
            ThongKeSach tk = new ThongKeSach();
            model.setNumRows(0);
            for(ThongKeSach s:listbookmanager){
                model.addRow(new Object[]{s.getMathongke(),s.getBookID(),s.getNgaythongke(),s.getSoluongton()});
            }
            model.fireTableDataChanged();
            OnOffButton(false, true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void laydulieuthongke(){
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        try{
            readandwritebookdata rw = new readandwritebookdata();
            listbookmanager = rw.docFileBook();
            ThongKeSach tk = new ThongKeSach();
            model.setNumRows(0);
            for(ThongKeSach s:listbookmanager){
                model.addRow(new Object[]{s.getMathongke(),s.getBookID(),s.getNgaythongke(),s.getSoluongton()});
            }
            model.fireTableDataChanged();
            OnOffButton(false, true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComeBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangthongke = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMSTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        AddBook = new javax.swing.JButton();
        UpdateBook = new javax.swing.JButton();
        DeleteBook = new javax.swing.JButton();
        SearchBook = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        NoConfirm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQuanlity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thống kê sách");

        ComeBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComeBack.setText("Quay lại");
        ComeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComeBackActionPerformed(evt);
            }
        });

        bangthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Mã số thống kê", "Mã sách", "Ngày thống kê", "Số lượng trong kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangthongkeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangthongke);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã số thống kê");

        txtMSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMSTKActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã sách");

        txtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIDActionPerformed(evt);
            }
        });

        AddBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddBook.setText("Thêm");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        UpdateBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateBook.setText("Cập nhật");
        UpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookActionPerformed(evt);
            }
        });

        DeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteBook.setText("Xóa");
        DeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookActionPerformed(evt);
            }
        });

        SearchBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchBook.setText("Tìm kiếm");
        SearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBookActionPerformed(evt);
            }
        });

        Confirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Confirm.setText("Đồng ý");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        NoConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NoConfirm.setText("Hủy bỏ");
        NoConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoConfirmActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày thống kê");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng tồn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComeBack)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95)
                                .addComponent(txtBookID, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMSTK, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtTime)
                                    .addComponent(txtQuanlity))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBook)
                            .addComponent(DeleteBook)
                            .addComponent(Confirm))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBook)
                            .addComponent(SearchBook)
                            .addComponent(NoConfirm))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(ComeBack))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBook)
                    .addComponent(UpdateBook))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteBook)
                            .addComponent(SearchBook)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuanlity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Confirm)
                        .addComponent(NoConfirm)))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMSTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMSTKActionPerformed

    private void txtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIDActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        OnOffButton(true, false);
        check = 1;
    }//GEN-LAST:event_AddBookActionPerformed

    private void ComeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComeBackActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ComeBackActionPerformed

    private void UpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookActionPerformed
        OnOffButton(true, false);
        check = -1;
    }//GEN-LAST:event_UpdateBookActionPerformed

    private void DeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookActionPerformed
        OnOffButton(true, false);
        check = -2;
    }//GEN-LAST:event_DeleteBookActionPerformed
    public static int tb = 0;
    private void SearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookActionPerformed
        outsearching(true, false);
        String id = this.txtMSTK.getText();
        DefaultTableModel model = (DefaultTableModel) this.bangthongke.getModel();
        model.setNumRows(0);
        for(ThongKeSach s:listbookmanager){
            if(id.equals(s.getMathongke())){
                tb++;
                model.addRow(new Object[]{s.getMathongke(),s.getBookID(),s.getNgaythongke(),s.getSoluongton()});
            }
        }
        if(tb == 0) JOptionPane.showConfirmDialog(this, "Khong co so thong ke phu hop", "Thong bao", JOptionPane.ERROR_MESSAGE);
        check = 2;
    }//GEN-LAST:event_SearchBookActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        String id = this.txtMSTK.getText();
        String bookid = this.txtBookID.getText();
        String date = this.txtTime.getText();
        String sl = this.txtQuanlity.getText();
        if(check == 1){
            try{
                readandwritebookdata rw = new readandwritebookdata();
                ThongKeSach s = new ThongKeSach(txtMSTK.getText(),txtBookID.getText(),txtTime.getText(),txtQuanlity.getText());
                listbookmanager.add(s);
                rw.luuFile(listbookmanager, false);
                JOptionPane.showMessageDialog(this, "Da luu thanh cong", "Trang thai", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        else if(check == -1){
            try{
                readandwritebookdata rw = new readandwritebookdata();
                ThongKeSach s = new ThongKeSach(txtMSTK.getText(),txtBookID.getText(),txtTime.getText(),txtQuanlity.getText());
                listbookmanager.set(position, s);
                rw.luuFile(listbookmanager, false);
                JOptionPane.showMessageDialog(this, "Da luu thanh cong", "Trang thai", JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        else if(check == -2){
            try{
                readandwritebookdata rw = new readandwritebookdata();
                listbookmanager.remove(position);
                JOptionPane.showConfirmDialog(this, "Da xoa thanh cong", "Trang thai", JOptionPane.ERROR_MESSAGE);
                rw.luuFile(listbookmanager, false);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        laydulieuthongke();
    }//GEN-LAST:event_ConfirmActionPerformed

    private void bangthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangthongkeMouseClicked
        position = this.bangthongke.getSelectedRow();
        ThongKeSach s = listbookmanager.get(position);
        this.txtMSTK.setText(s.getMathongke());
        this.txtBookID.setText(s.getBookID());
        this.txtTime.setText(s.getNgaythongke());
        this.txtQuanlity.setText(s.getSoluongton());
    }//GEN-LAST:event_bangthongkeMouseClicked

    private void NoConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoConfirmActionPerformed
        this.txtMSTK.setText("");
        this.txtBookID.setText("");
        this.txtTime.setText("");
        this.txtQuanlity.setText("");
        OnOffButton(false, true);
        if(check == 2){
            laydulieuthongke();
        }
    }//GEN-LAST:event_NoConfirmActionPerformed

    private void OnOffButton(boolean a, boolean b){
        this.Confirm.show(a);
        this.NoConfirm.show(a);
        this.AddBook.show(b);
        this.DeleteBook.show(b);
        this.SearchBook.show(b);
        this.UpdateBook.show(b);
    }
    private void outsearching(boolean a, boolean b){
        this.NoConfirm.show(a);
        this.Confirm.show(b);
        this.AddBook.show(b);
        this.DeleteBook.show(b);
        this.SearchBook.show(b);
        this.UpdateBook.show(b);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton ComeBack;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton DeleteBook;
    private javax.swing.JButton NoConfirm;
    private javax.swing.JButton SearchBook;
    private javax.swing.JButton UpdateBook;
    private javax.swing.JTable bangthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtMSTK;
    private javax.swing.JTextField txtQuanlity;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
